
name: OMICRON2
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - black
  - jupyter
  - matplotlib
  - numpy
  - python=3.10
  - pandas
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - termcolor
  - torchvision
  - tqdm
  - tensorboard
  - pip:
    - pyraws
    - ipywidgets
    - ipympl
